name: ukan
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - scipy=1.15.2
  - pandas=2.3.0
  - scikit-learn=1.7.0
  - scikit-image=0.25.2
  - matplotlib=3.10.6
  - opencv=4.12.0
  - imageio=2.37.0
  - imagecodecs=2025.3.30
  - tifffile=2025.5.10
  - pillow=11.3.0
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - tqdm=4.67.1
  - jinja2=3.1.6
  - joblib=1.5.2
  - networkx=3.4.2
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - albucore==0.0.24
    - albumentations==2.0.8
    - annotated-types==0.7.0
    - contourpy==1.3.2
    - medpy==0.5.2
    - simpleitk==2.5.2
    - pydantic==2.11.7
    - typing-inspection==0.4.1
    - triton
    - tiatoolbox
